import type { Category } from './types';

export const SEED_CATEGORIES: Omit<Category, 'id'>[] = [
  {
    name: 'Indian Slangs',
    emoji: '🗣️',
    locale: 'in',
    isOfficial: true,
    entries: [
      { word: 'Jugaad', hint: 'Hack' },
      { word: 'Bindaas', hint: 'Carefree' },
      { word: 'Yaar', hint: 'Friend' },
      { word: 'Timepass', hint: 'Boredom' },
      { word: 'Bakwaas', hint: 'Nonsense' },
      { word: 'Pakka', hint: 'Confirmed' },
      { word: 'Mast', hint: 'Awesome' },
      { word: 'Chamcha', hint: 'Sycophant' },
      { word: 'Patakha', hint: 'Firecracker' },
      { word: 'Filmy', hint: 'Dramatic' },
      { word: 'Desi', hint: 'Local' },
      { word: 'Vella', hint: 'Idle' },
      { word: 'Kaand', hint: 'Scandal' },
      { word: 'Bawaal', hint: 'Chaos' },
      { word: 'Tashan', hint: 'Style' },
      { word: 'Locha', hint: 'Trouble' },
      { word: 'Faltu', hint: 'Useless' },
      { word: 'Bhai', hint: 'Brother' },
      { word: 'Funda', hint: 'Concept' },
      { word: 'Scene', hint: 'Situation' },
    ],
  },
  {
    name: 'Indian Snacks & Food',
    emoji: '🍛',
    locale: 'in',
    isOfficial: true,
    entries: [
      { word: 'Biryani', hint: 'Rice' },
      { word: 'Samosa', hint: 'Triangle' },
      { word: 'Pani Puri', hint: 'Crunch' },
      { word: 'Vada Pav', hint: 'Burger' },
      { word: 'Dosa', hint: 'Crepe' },
      { word: 'Idli', hint: 'Steam' },
      { word: 'Pav Bhaji', hint: 'Mash' },
      { word: 'Chole Bhature', hint: 'Chickpea' },
      { word: 'Rajma Chawal', hint: 'Comfort' },
      { word: 'Gulab Jamun', hint: 'Syrup' },
      { word: 'Jalebi', hint: 'Spiral' },
      { word: 'Lassi', hint: 'Yogurt' },
      { word: 'Masala Chai', hint: 'Spice' },
      { word: 'Paneer Tikka', hint: 'Skewer' },
      { word: 'Aloo Paratha', hint: 'Stuffed' },
      { word: 'Rasgulla', hint: 'Sponge' },
      { word: 'Dhokla', hint: 'Yellow' },
      { word: 'Kachori', hint: 'Fried' },
      { word: 'Bhel Puri', hint: 'Tangy' },
      { word: 'Misal Pav', hint: 'Spicy' },
    ],
  },
  {
    name: 'Bollywood Movies',
    emoji: '🎬',
    locale: 'in',
    isOfficial: true,
    entries: [
      { word: 'Sholay', hint: 'Dacoit' },
      { word: 'DDLJ', hint: 'Train' },
      { word: '3 Idiots', hint: 'College' },
      { word: 'Lagaan', hint: 'Cricket' },
      { word: 'Baahubali', hint: 'Waterfall' },
      { word: 'Dangal', hint: 'Wrestling' },
      { word: 'ZNMD', hint: 'Spain' },
      { word: 'Kabhi Khushi Kabhie Gham', hint: 'Family' },
      { word: 'Andaz Apna Apna', hint: 'Comedy' },
      { word: 'Mughal-e-Azam', hint: 'Mughal' },
      { word: 'Gully Boy', hint: 'Rap' },
      { word: 'Queen', hint: 'Solo' },
      { word: 'PK', hint: 'Alien' },
      { word: 'Munna Bhai MBBS', hint: 'Doctor' },
      { word: 'Dil Chahta Hai', hint: 'Goa' },
      { word: 'Taare Zameen Par', hint: 'Child' },
      { word: 'Student of the Year', hint: 'Campus' },
      { word: 'Gangs of Wasseypur', hint: 'Coal' },
      { word: 'Rang De Basanti', hint: 'Patriot' },
      { word: 'Kaho Naa Pyaar Hai', hint: 'Debut' },
    ],
  },
  {
    name: 'Indian Cricketers',
    emoji: '🏏',
    locale: 'in',
    isOfficial: true,
    entries: [
      { word: 'Sachin Tendulkar', hint: 'Bat' },
      { word: 'MS Dhoni', hint: 'Helicopter' },
      { word: 'Virat Kohli', hint: 'Chase' },
      { word: 'Rohit Sharma', hint: 'Pull-shot' },
      { word: 'Kapil Dev', hint: '1983' },
      { word: 'Sourav Ganguly', hint: 'Dada' },
      { word: 'Rahul Dravid', hint: 'Wall' },
      { word: 'Yuvraj Singh', hint: 'Six-sixes' },
      { word: 'Anil Kumble', hint: 'Spin' },
      { word: 'Sunil Gavaskar', hint: 'Opener' },
      { word: 'Jasprit Bumrah', hint: 'Yorker' },
      { word: 'Hardik Pandya', hint: 'Allrounder' },
      { word: 'Shubman Gill', hint: 'Youngling' },
      { word: 'KL Rahul', hint: 'Keeper' },
      { word: 'Ravindra Jadeja', hint: 'Fielding' },
      { word: 'Ravi Shastri', hint: 'Coach' },
      { word: 'Harbhajan Singh', hint: 'Turbanator' },
      { word: 'VVS Laxman', hint: 'Wristy' },
      { word: 'Vinoo Mankad', hint: 'Runout' },
      { word: 'Zaheer Khan', hint: 'Swing' },
    ],
  },
  {
    name: 'Indian Festivals',
    emoji: '🪔',
    locale: 'in',
    isOfficial: true,
    entries: [
      { word: 'Diwali', hint: 'Lights' },
      { word: 'Holi', hint: 'Colours' },
      { word: 'Eid', hint: 'Crescent' },
      { word: 'Ganesh Chaturthi', hint: 'Idol' },
      { word: 'Navratri', hint: 'Garba' },
      { word: 'Onam', hint: 'Boat' },
      { word: 'Pongal', hint: 'Harvest' },
      { word: 'Raksha Bandhan', hint: 'Thread' },
      { word: 'Karwa Chauth', hint: 'Moon' },
      { word: 'Lohri', hint: 'Bonfire' },
      { word: 'Durga Puja', hint: 'Pandal' },
      { word: 'Janmashtami', hint: 'Krishna' },
      { word: 'Makar Sankranti', hint: 'Kite' },
      { word: 'Christmas', hint: 'Tree' },
      { word: 'Baisakhi', hint: 'Harvest' },
      { word: 'Eid ul-Fitr', hint: 'Sweet' },
      { word: 'Guru Nanak Jayanti', hint: 'Sikh' },
      { word: 'Vasant Panchami', hint: 'Yellow' },
    ],
  },
  {
    name: 'Indian Cities',
    emoji: '🏙️',
    locale: 'in',
    isOfficial: true,
    entries: [
      { word: 'Mumbai', hint: 'Beach' },
      { word: 'Delhi', hint: 'Capital' },
      { word: 'Bengaluru', hint: 'Tech' },
      { word: 'Kolkata', hint: 'Howrah' },
      { word: 'Chennai', hint: 'Marina' },
      { word: 'Hyderabad', hint: 'Pearls' },
      { word: 'Jaipur', hint: 'Pink' },
      { word: 'Lucknow', hint: 'Nawab' },
      { word: 'Goa', hint: 'Sand' },
      { word: 'Varanasi', hint: 'Ghats' },
      { word: 'Pune', hint: 'Hills' },
      { word: 'Ahmedabad', hint: 'Cotton' },
      { word: 'Chandigarh', hint: 'Planned' },
      { word: 'Kochi', hint: 'Backwater' },
      { word: 'Shimla', hint: 'Snow' },
      { word: 'Agra', hint: 'Taj' },
      { word: 'Amritsar', hint: 'Golden' },
      { word: 'Jodhpur', hint: 'Blue' },
      { word: 'Mysuru', hint: 'Palace' },
      { word: 'Udaipur', hint: 'Lake' },
    ],
  },
  {
    name: 'Desi Vibes',
    emoji: '🛺',
    locale: 'in',
    isOfficial: true,
    entries: [
      { word: 'Auto rickshaw', hint: 'Three-wheeler' },
      { word: 'Rangoli', hint: 'Pattern' },
      { word: 'Saree', hint: 'Drape' },
      { word: 'Chai stall', hint: 'Tea' },
      { word: 'Gully cricket', hint: 'Lane' },
      { word: 'Bollywood dance', hint: 'Step' },
      { word: 'Pressure cooker whistle', hint: 'Steam' },
      { word: 'Maggi', hint: 'Noodles' },
      { word: 'Chappal', hint: 'Slipper' },
      { word: 'Antakshari', hint: 'Song' },
      { word: "Cousin's wedding", hint: 'Sangeet' },
      { word: 'Train pantry chai', hint: 'Rail' },
      { word: 'IPL final', hint: 'Trophy' },
      { word: 'Kirana store', hint: 'Corner' },
      { word: 'Jugadu helmet', hint: 'Safety' },
      { word: 'Buffer wedding', hint: 'Late' },
      { word: 'Morning newspaper', hint: 'Chai' },
      { word: 'Dabbawala', hint: 'Tiffin' },
      { word: 'Pinni', hint: 'Sweet' },
      { word: 'Lota', hint: 'Water' },
    ],
  },
  {
    name: 'Animals',
    emoji: '🦁',
    locale: 'global',
    isOfficial: true,
    entries: [
      { word: 'Elephant', hint: 'Trunk' },
      { word: 'Penguin', hint: 'Ice' },
      { word: 'Giraffe', hint: 'Neck' },
      { word: 'Dolphin', hint: 'Smart' },
      { word: 'Kangaroo', hint: 'Pouch' },
      { word: 'Cheetah', hint: 'Speed' },
      { word: 'Octopus', hint: 'Tentacles' },
      { word: 'Peacock', hint: 'Feather' },
      { word: 'Panda', hint: 'Bamboo' },
      { word: 'Wolf', hint: 'Pack' },
      { word: 'Chameleon', hint: 'Colour' },
      { word: 'Gorilla', hint: 'Silverback' },
      { word: 'Flamingo', hint: 'Pink' },
      { word: 'Shark', hint: 'Fin' },
      { word: 'Koala', hint: 'Eucalyptus' },
      { word: 'Tiger', hint: 'Stripes' },
      { word: 'Bat', hint: 'Sonar' },
      { word: 'Sloth', hint: 'Slow' },
      { word: 'Axolotl', hint: 'Salamander' },
      { word: 'Platypus', hint: 'Weird' },
    ],
  },
  {
    name: 'Hollywood Movies',
    emoji: '🎥',
    locale: 'global',
    isOfficial: true,
    entries: [
      { word: 'Inception', hint: 'Dream' },
      { word: 'The Dark Knight', hint: 'Joker' },
      { word: 'Avengers: Endgame', hint: 'Snap' },
      { word: 'Titanic', hint: 'Iceberg' },
      { word: 'The Matrix', hint: 'Pill' },
      { word: 'Interstellar', hint: 'Wormhole' },
      { word: 'The Lion King', hint: 'Simba' },
      { word: 'Forrest Gump', hint: 'Shrimp' },
      { word: 'Pulp Fiction', hint: 'Briefcase' },
      { word: 'The Godfather', hint: 'Offer' },
      { word: 'Jurassic Park', hint: 'Dinosaur' },
      { word: 'Spider-Man', hint: 'Swing' },
      { word: 'Home Alone', hint: 'Trap' },
      { word: 'Back to the Future', hint: 'DeLorean' },
      { word: 'The Shawshank Redemption', hint: 'Prison' },
      { word: 'Get Out', hint: 'Sunken' },
      { word: 'La La Land', hint: 'Jazz' },
      { word: 'Everything Everywhere All at Once', hint: 'Multiverse' },
      { word: 'Parasite', hint: 'Basement' },
      { word: 'Whiplash', hint: 'Drums' },
    ],
  },
  {
    name: 'Sports',
    emoji: '⚽',
    locale: 'global',
    isOfficial: true,
    entries: [
      { word: 'Football', hint: 'Offside' },
      { word: 'Basketball', hint: 'Dunk' },
      { word: 'Tennis', hint: 'Ace' },
      { word: 'Swimming', hint: 'Lap' },
      { word: 'Gymnastics', hint: 'Vault' },
      { word: 'Boxing', hint: 'Jab' },
      { word: 'Golf', hint: 'Birdie' },
      { word: 'Badminton', hint: 'Shuttle' },
      { word: 'Volleyball', hint: 'Spike' },
      { word: 'Wrestling', hint: 'Pin' },
      { word: 'Archery', hint: 'Bullseye' },
      { word: 'Cycling', hint: 'Peloton' },
      { word: 'Skateboarding', hint: 'Ollie' },
      { word: 'Rowing', hint: 'Oar' },
      { word: 'Polo', hint: 'Mallet' },
      { word: 'Snooker', hint: 'Cue' },
      { word: 'Fencing', hint: 'Épée' },
      { word: 'Surfing', hint: 'Wave' },
      { word: 'Ice Hockey', hint: 'Puck' },
      { word: 'Rugby', hint: 'Scrum' },
    ],
  },
  {
    name: 'Countries',
    emoji: '🌍',
    locale: 'global',
    isOfficial: true,
    entries: [
      { word: 'Japan', hint: 'Sushi' },
      { word: 'Brazil', hint: 'Carnival' },
      { word: 'France', hint: 'Baguette' },
      { word: 'Egypt', hint: 'Pyramid' },
      { word: 'Australia', hint: 'Kangaroo' },
      { word: 'Russia', hint: 'Matryoshka' },
      { word: 'Mexico', hint: 'Taco' },
      { word: 'Italy', hint: 'Pasta' },
      { word: 'China', hint: 'Dragon' },
      { word: 'Canada', hint: 'Maple' },
      { word: 'Greece', hint: 'Olive' },
      { word: 'Kenya', hint: 'Safari' },
      { word: 'Norway', hint: 'Fjord' },
      { word: 'Peru', hint: 'Machu Picchu' },
      { word: 'South Korea', hint: 'K-pop' },
      { word: 'Turkey', hint: 'Bosphorus' },
      { word: 'Argentina', hint: 'Tango' },
      { word: 'Ethiopia', hint: 'Coffee' },
      { word: 'Iceland', hint: 'Aurora' },
      { word: 'Thailand', hint: 'Temple' },
    ],
  },
  {
    name: 'Professions',
    emoji: '👩‍⚕️',
    locale: 'global',
    isOfficial: true,
    entries: [
      { word: 'Surgeon', hint: 'Scalpel' },
      { word: 'Astronaut', hint: 'Orbit' },
      { word: 'Chef', hint: 'Knife' },
      { word: 'Architect', hint: 'Blueprint' },
      { word: 'Firefighter', hint: 'Hose' },
      { word: 'Pilot', hint: 'Cockpit' },
      { word: 'Archaeologist', hint: 'Dig' },
      { word: 'Judge', hint: 'Gavel' },
      { word: 'Magician', hint: 'Trick' },
      { word: 'Librarian', hint: 'Catalog' },
      { word: 'Marine Biologist', hint: 'Coral' },
      { word: 'Sommelier', hint: 'Wine' },
      { word: 'Stuntman', hint: 'Fall' },
      { word: 'Translator', hint: 'Language' },
      { word: 'Game Developer', hint: 'Code' },
      { word: 'Forensic Scientist', hint: 'Evidence' },
      { word: 'Diplomat', hint: 'Embassy' },
      { word: 'Beekeeper', hint: 'Hive' },
      { word: 'Puppeteer', hint: 'String' },
      { word: 'Taxidermist', hint: 'Preserve' },
    ],
  },
  {
    name: 'Superheroes',
    emoji: '🦸',
    locale: 'global',
    isOfficial: true,
    entries: [
      { word: 'Superman', hint: 'Kryptonite' },
      { word: 'Batman', hint: 'Cave' },
      { word: 'Wonder Woman', hint: 'Lasso' },
      { word: 'Spider-Man', hint: 'Web' },
      { word: 'Iron Man', hint: 'Suit' },
      { word: 'Thor', hint: 'Hammer' },
      { word: 'Captain America', hint: 'Shield' },
      { word: 'Black Widow', hint: 'Spy' },
      { word: 'Doctor Strange', hint: 'Mystic' },
      { word: 'Black Panther', hint: 'Wakanda' },
      { word: 'Aquaman', hint: 'Trident' },
      { word: 'The Flash', hint: 'Lightning' },
      { word: 'Deadpool', hint: 'Mercenary' },
      { word: 'Wolverine', hint: 'Claws' },
      { word: 'Green Lantern', hint: 'Ring' },
      { word: 'Shazam', hint: 'Lightning' },
      { word: 'Ant-Man', hint: 'Tiny' },
      { word: 'Hawkeye', hint: 'Arrow' },
      { word: 'Scarlet Witch', hint: 'Chaos' },
      { word: 'Shang-Chi', hint: 'Rings' },
    ],
  },
  {
    name: 'Things in a Kitchen',
    emoji: '🍳',
    locale: 'global',
    isOfficial: true,
    entries: [
      { word: 'Refrigerator', hint: 'Cool' },
      { word: 'Blender', hint: 'Smoothie' },
      { word: 'Spatula', hint: 'Flip' },
      { word: 'Colander', hint: 'Drain' },
      { word: 'Rolling Pin', hint: 'Dough' },
      { word: 'Whisk', hint: 'Egg' },
      { word: 'Chopping Board', hint: 'Cut' },
      { word: 'Wok', hint: 'Stir-fry' },
      { word: 'Ladle', hint: 'Soup' },
      { word: 'Peeler', hint: 'Skin' },
      { word: 'Tongs', hint: 'Grip' },
      { word: 'Mortar and Pestle', hint: 'Grind' },
      { word: 'Thermometer', hint: 'Temperature' },
      { word: 'Can Opener', hint: 'Tin' },
      { word: 'Grater', hint: 'Shred' },
      { word: 'Pressure Cooker', hint: 'Steam' },
      { word: 'Toaster', hint: 'Bread' },
      { word: 'Microwave', hint: 'Reheat' },
      { word: 'Skillet', hint: 'Pan' },
      { word: 'Oven Mitt', hint: 'Hot' },
    ],
  },
  {
    name: 'Desi 00s Kids',
    emoji: '📺',
    locale: 'in',
    isOfficial: true,
    entries: [
      { word: 'Shaka Laka Boom Boom', hint: 'Lead' },
      { word: "Takeshi's Castle", hint: 'Honeycomb' },
      { word: 'Doraemon', hint: 'Bureau' },
      { word: 'Pokemon', hint: 'Mustard' },
      { word: 'Beyblade', hint: 'Spin' },
      { word: 'Power Rangers', hint: 'Spandex' },
    ],
  },
  {
    name: 'Instagram Brainrot',
    emoji: '📱',
    locale: 'global',
    isOfficial: true,
    entries: [
      { word: 'Moye Moye', hint: 'Wrist' },
      { word: 'Looking like a wow', hint: 'Sober' },
      { word: 'Systems', hint: 'Fortuner' },
      { word: 'Aura', hint: 'Minus' },
      { word: 'Skibidi', hint: 'Porcelain' },
      { word: 'Bhupendra Jogi', hint: 'Diary' },
    ],
  },
  {
    name: 'Bollywood',
    emoji: '🎬',
    locale: 'in',
    isOfficial: true,
    entries: [
      { word: 'Shah Rukh Khan', hint: 'Epiglottis' },
      { word: 'Salman Khan', hint: 'Footpath' },
      { word: 'Ranbir Kapoor', hint: 'Towel' },
      { word: 'Alia Bhatt', hint: 'Geography' },
      { word: 'Zindagi Na Milegi Dobara', hint: 'Bagwati' },
      { word: 'Animal', hint: 'Pelvis' },
      { word: '3 Idiots', hint: 'Silencer' },
      { word: 'Kabir Singh', hint: 'Injection' },
      { word: 'Deepika Padukone', hint: 'Badminton' },
      { word: 'Hrithik Roshan', hint: 'Thumb' },
    ],
  },
  {
    name: 'South Cinema',
    emoji: '🎥',
    locale: 'in',
    isOfficial: true,
    entries: [
      { word: 'Pushpa', hint: 'Chappal' },
      { word: 'RRR', hint: 'Physics' },
      { word: 'Bahubali', hint: 'Waterfall' },
      { word: 'KGF', hint: 'Cigarette' },
      { word: 'Jailer', hint: 'Glasses' },
      { word: 'Leo', hint: 'Coffee' },
      { word: 'Kantara', hint: 'Echo' },
      { word: 'Vikram', hint: 'Rooster' },
    ],
  },
  {
    name: 'Anime',
    emoji: '⚔️',
    locale: 'global',
    isOfficial: true,
    entries: [
      { word: 'Naruto', hint: 'Swing' },
      { word: 'Death Note', hint: 'Potato' },
      { word: 'One Piece', hint: 'Rubber' },
      { word: 'Attack on Titan', hint: 'Basement' },
      { word: 'Jujutsu Kaisen', hint: 'Blindfold' },
      { word: 'Demon Slayer', hint: 'Bamboo' },
    ],
  },
  {
    name: 'Cricket',
    emoji: '🏏',
    locale: 'in',
    isOfficial: true,
    entries: [
      { word: 'Virat Kohli', hint: 'Brussels' },
      { word: 'MS Dhoni', hint: 'Military' },
      { word: 'Rohit Sharma', hint: 'Forgetful' },
      { word: 'Hardik Pandya', hint: 'Koffee' },
      { word: 'Shubman Gill', hint: 'Sara' },
      { word: 'Gautam Gambhir', hint: 'Credit' },
      { word: 'Ravichandran Ashwin', hint: 'Mankad' },
      { word: 'IPL', hint: 'Strategy' },
    ],
  },
  {
    name: 'Indian Politics',
    emoji: '🗳️',
    locale: 'in',
    isOfficial: true,
    entries: [
      { word: 'Narendra Modi', hint: 'Radar' },
      { word: 'Rahul Gandhi', hint: 'Gold' },
      { word: 'Arvind Kejriwal', hint: 'Muffler' },
      { word: 'Mamata Banerjee', hint: 'Hamba' },
      { word: 'Amit Shah', hint: 'Chronology' },
    ],
  },
  {
    name: 'World History',
    emoji: '🌍',
    locale: 'global',
    isOfficial: true,
    entries: [
      { word: 'Titanic', hint: 'Door space' },
      { word: 'Napoleon', hint: 'Short king' },
      { word: 'Hiroshima', hint: 'Mushroom cloud' },
      { word: 'Cold War', hint: 'Space race' },
      { word: 'Great Wall', hint: 'Visible moon' },
    ],
  },
  {
    name: 'Indian History',
    emoji: '🏛️',
    locale: 'in',
    isOfficial: true,
    entries: [
      { word: 'Dandi March', hint: 'Free salt' },
      { word: 'Ashoka', hint: 'Stone pillar' },
      { word: 'Chanakya', hint: 'Tuft knot' },
      { word: 'Partition', hint: 'Radcliffe line' },
      { word: '1857 Revolt', hint: 'Greased cartridge' },
    ],
  },
  {
    name: 'Geography',
    emoji: '🗺️',
    locale: 'in',
    isOfficial: true,
    entries: [
      { word: 'Ladakh', hint: 'Cold desert' },
      { word: 'Cherrapunji', hint: 'Cloud home' },
      { word: 'Thar', hint: 'Ship animal' },
      { word: 'Ganges', hint: 'Sin cleaner' },
    ],
  },
  {
    name: 'World Geography',
    emoji: '🌐',
    locale: 'global',
    isOfficial: true,
    entries: [
      { word: 'Mount Everest', hint: 'Zero oxygen' },
      { word: 'Dead Sea', hint: 'Salt float' },
      { word: 'Amazon', hint: "Earth's lungs" },
    ],
  },
  {
    name: 'Sports in India',
    emoji: '🏅',
    locale: 'in',
    isOfficial: true,
    entries: [
      { word: 'Neeraj Chopra', hint: 'Pointy stick' },
      { word: 'Kabaddi', hint: 'Breath hold' },
      { word: 'Sunil Chhetri', hint: 'Captain fantastic' },
    ],
  },
  {
    name: 'Hindu Mythology',
    emoji: '🪔',
    locale: 'in',
    isOfficial: true,
    entries: [
      { word: 'Krishna', hint: 'Charioteer' },
      { word: 'Arjuna', hint: 'Pupil' },
      { word: 'Bhishma', hint: 'Bed' },
      { word: 'Draupadi', hint: 'Dice' },
      { word: 'Karna', hint: 'Alms' },
      { word: 'Abhimanyu', hint: 'Labyrinth' },
      { word: 'Rama', hint: 'Exile' },
      { word: 'Sita', hint: 'Furrow' },
      { word: 'Hanuman', hint: 'Sun' },
      { word: 'Ravana', hint: 'Melody' },
      { word: 'Lakshmana', hint: 'Vigil' },
      { word: 'Kumbhakarna', hint: 'Season' },
      { word: 'Shiva', hint: 'Ash' },
      { word: 'Ganesha', hint: 'Scribe' },
      { word: 'Vishnu', hint: 'Preservation' },
      { word: 'Durga', hint: 'Trident' },
      { word: 'Amrit', hint: 'Nectar' },
      { word: 'Yudhishthira', hint: 'Dog' },
      { word: 'Eklavya', hint: 'Thumb' },
      { word: 'Ashwatthama', hint: 'Gem' },
      { word: 'Indrajit', hint: 'Mist' },
      { word: 'Ghatotkacha', hint: 'Giant' },
      { word: 'Parshurama', hint: 'Axe' },
      { word: 'Narasimha', hint: 'Pillar' },
      { word: 'Vamana', hint: 'Footprint' },
      { word: 'Matsya', hint: 'Gills' },
      { word: 'Kurma', hint: 'Shell' },
      { word: 'Varaha', hint: 'Tusk' },
      { word: 'Valmiki', hint: 'Ant' },
      { word: 'Shakuni', hint: 'Ivory' },
      { word: 'Gandhari', hint: 'Blindfold' },
      { word: 'Dhritarashtra', hint: 'Ambition' },
      { word: 'Kunti', hint: 'Mantra' },
      { word: 'Madri', hint: 'Fire' },
      { word: 'Sahadeva', hint: 'Future' },
      { word: 'Nakula', hint: 'Beauty' },
      { word: 'Balarama', hint: 'Plough' },
      { word: 'Sudama', hint: 'Poha' },
      { word: 'Putana', hint: 'Milk' },
      { word: 'Kans', hint: 'Prison' },
      { word: 'Bharat', hint: 'Sandals' },
      { word: 'Kaikeyi', hint: 'Promise' },
      { word: 'Surpanakha', hint: 'Nose' },
      { word: 'Jatayu', hint: 'Wing' },
      { word: 'Shabari', hint: 'Berry' },
      { word: 'Bali', hint: 'Tail' },
      { word: 'Sugriva', hint: 'Cave' },
      { word: 'Angada', hint: 'Leg' },
      { word: 'Vibhishana', hint: 'Traitor' },
      { word: 'Mandodari', hint: 'Wisdom' },
    ],
  },
];
