import type { Category } from './types';

export const SEED_CATEGORIES: Omit<Category, 'id'>[] = [
  {
    name: 'Famous People',
    emoji: '🌟',
    locale: 'global',
    isOfficial: true,
    entries: [
      { word: 'Shah Rukh Khan', hint: 'overhyped' },
      { word: 'Salman Khan', hint: 'buddha' },
      { word: 'Aamir Khan', hint: 'vanvas' },
      { word: 'Ranveer Singh', hint: 'loud' },
      { word: 'Akshay Kumar', hint: 'videshi' },
      { word: 'Hrithik Roshan', hint: 'thumka' },
      { word: 'Saif Ali Khan', hint: 'ghuspaith' },
      { word: 'Ranbir Kapoor', hint: 'chimney' },
      { word: 'Ajay Devgn', hint: 'tobacco' },
      { word: 'Govinda', hint: 'purana' },
      { word: 'Amitabh Bachchan', hint: 'baritone' },
      { word: 'Anil Kapoor', hint: 'anjawan' },
      { word: 'Sunny Deol', hint: 'akela' },
      { word: 'Vicky Kaushal', hint: 'joshila' },
      { word: 'Kartik Aaryan', hint: 'bhasad' },
      { word: 'Sushant Singh Rajput', hint: 'stargazer' },
      { word: 'Nawazuddin Siddiqui', hint: 'kabhi' },
      { word: 'Pankaj Tripathi', hint: 'carpet' },
      { word: 'Manoj Bajpayee', hint: 'majburi' },
      { word: 'Rajkummar Rao', hint: 'trapped' },
      { word: 'Ayushmann Khurrana', hint: 'alag' },
      { word: 'Tiger Shroff', hint: 'khaali' },
      { word: 'Varun Dhawan', hint: 'papaboy' },
      { word: 'Deepika Padukone', hint: 'depressed' },
      { word: 'Priyanka Chopra', hint: 'videshi-dulha' },
      { word: 'Alia Bhatt', hint: 'iq' },
      { word: 'Kareena Kapoor', hint: 'starry' },
      { word: 'Katrina Kaif', hint: 'broken-hindi' },
      { word: 'Anushka Sharma', hint: 'captain-ki' },
      { word: 'Kiara Advani', hint: 'thappad' },
      { word: 'Janhvi Kapoor', hint: 'gymrat' },
      { word: 'Ananya Panday', hint: 'struggle' },
      { word: 'Sara Ali Khan', hint: 'namaste-darshako' },
      { word: 'Shraddha Kapoor', hint: 'sneeze' },
      { word: 'Madhuri Dixit', hint: 'dimple' },
      { word: 'Sridevi', hint: 'dubai-tub' },
      { word: 'Aishwarya Rai', hint: 'purple' },
      { word: 'Rekha', hint: 'raat-ki-rani' },
      { word: 'Mallaika Arora', hint: 'young-bf' },
      { word: 'Disha Patani', hint: 'abs' },
      { word: 'Jacqueline Fernandez', hint: 'scammer-gift' },
      { word: 'Nora Fatehi', hint: 'morocco' },
      { word: 'Sunny Leone', hint: 'incognito' },
      { word: 'Urfi Javed', hint: 'scotch-tape' },
      { word: 'Rashmika Mandanna', hint: 'ai-clone' },
      { word: 'Kim Kardashian', hint: 'plastic' },
      { word: 'Taylor Swift', hint: 'ex-list' },
      { word: 'Justin Bieber', hint: 'selena' },
      { word: 'Kanye West', hint: 'rant' },
      { word: 'Beyonce', hint: 'queen-b' },
      { word: 'Rihanna', hint: 'ambani-naachi' },
      { word: 'Selena Gomez', hint: 'kidney' },
      { word: 'Ariana Grande', hint: 'ponytail' },
      { word: 'Dwayne Johnson', hint: 'eyebrow' },
      { word: 'Tom Cruise', hint: 'cult' },
      { word: 'Leonardo DiCaprio', hint: 'twentyfive' },
      { word: 'Brad Pitt', hint: 'divorce' },
      { word: 'Will Smith', hint: 'oscar-slap' },
      { word: 'Johnny Depp', hint: 'amber-finger' },
      { word: 'Elon Musk', hint: 'twitter-daddy' },
      { word: 'Mark Zuckerberg', hint: 'lizard' },
      { word: 'Donald Trump', hint: 'wall' },
      { word: 'Lady Gaga', hint: 'meat-dress' },
      { word: 'Drake', hint: 'kendrick-beef' },
      { word: 'Kylie Jenner', hint: 'lipkit' },
      { word: 'Narendra Modi', hint: 'chai' },
      { word: 'Rahul Gandhi', hint: 'amul-baby' },
      { word: 'Arvind Kejriwal', hint: 'muffler' },
      { word: 'Mamata Banerjee', hint: 'bengal-didi' },
      { word: 'Amit Shah', hint: 'chanakya' },
      { word: 'Yogi Adityanath', hint: 'saffron-bulldozer' },
      { word: 'Sonia Gandhi', hint: 'italia-bahu' },
      { word: 'Nitish Kumar', hint: 'paltu' },
      { word: 'Lalu Yadav', hint: 'chara' },
      { word: 'Sharad Pawar', hint: 'ncp-chacha' },
      { word: 'Shashi Tharoor', hint: 'vocab' },
      { word: 'Smriti Irani', hint: 'tulsi' },
      { word: 'Asaduddin Owaisi', hint: 'topi-speech' },
      { word: 'Akhilesh Yadav', hint: 'cycle' },
      { word: 'Mayawati', hint: 'haathi' },
      { word: 'Uddhav Thackeray', hint: 'split-sena' },
      { word: 'Devendra Fadnavis', hint: 'wapas' },
      { word: 'Pragya Thakur', hint: 'saadhvi' },
      { word: 'Kanhaiya Kumar', hint: 'jnu' },
      { word: 'Imran Khan', hint: 'captain-jail' },
      { word: 'Mahira Khan', hint: 'humsafar' },
      { word: 'Fawad Khan', hint: 'khoobsurat' },
      { word: 'Hania Aamir', hint: 'babar-leak' },
      { word: 'Atif Aslam', hint: 'rockstar' },
      { word: 'Rahat Fateh Ali Khan', hint: 'chappal' },
      { word: 'Ali Zafar', hint: 'metoo' },
      { word: 'Sajal Aly', hint: 'yakeen' },
      { word: 'Aima Baig', hint: 'shahbaz' },
      { word: 'Iqra Aziz', hint: 'yasir' },
      { word: 'Sanam Saeed', hint: 'kashaf' },
      { word: 'Hamza Ali Abbasi', hint: 'preacher-actor' },
      { word: 'Nawaz Sharif', hint: 'panama' },
      { word: 'Maryam Nawaz', hint: 'abbu-ki-beti' },
      { word: 'Bilawal Bhutto', hint: 'hello-democracy' },
      { word: 'Ayeza Khan', hint: 'merepaas-tum' },
      { word: 'Junaid Jamshed', hint: 'tabligh' },
      { word: 'Rakhi Sawant', hint: 'matan-tataita' },
      { word: 'Sidharth Shukla', hint: 'sidnaaz' },
      { word: 'Shehnaz Gill', hint: 'punjab-katrina' },
      { word: 'Hina Khan', hint: 'akshara' },
      { word: 'Arshi Khan', hint: 'afridi-fan' },
      { word: 'Karan Kundra', hint: 'tejasswi' },
      { word: 'Tejasswi Prakash', hint: 'naagin' },
      { word: 'Munmun Dutta', hint: 'babita' },
      { word: 'Asim Riaz', hint: 'kashmiri' },
      { word: 'Devoleena Bhattacharjee', hint: 'gopi-bahu' },
      { word: 'Dolly Bindra', hint: 'bachgaya' },
      { word: 'Pooja Misrra', hint: 'khira' },
      { word: 'Swami Om', hint: 'mootra' },
      { word: 'Kamaal R Khan', hint: 'krk-review' },
      { word: 'Manoj Tiwari', hint: 'bhojpuri' },
      { word: 'Abdu Rozik', hint: 'tajik' },
      { word: 'CarryMinati', hint: 'yalgaar' },
      { word: 'BB Ki Vines', hint: 'titu' },
      { word: 'Ranveer Allahbadia', hint: 'parents-line' },
      { word: 'Tanmay Bhat', hint: 'ozempic' },
      { word: 'Samay Raina', hint: 'banned-chess' },
      { word: 'Ashish Chanchlani', hint: 'wassup' },
      { word: 'Harsh Beniwal', hint: 'vines-bhabhi' },
      { word: 'Bhuvan Bam', hint: 'dhindora' },
      { word: 'Amit Bhadana', hint: 'haryanvi' },
      { word: 'Triggered Insaan', hint: 'live-trigger' },
      { word: 'Elvish Yadav', hint: 'saanp-party' },
      { word: 'Sourav Joshi', hint: 'vlogger-bhai' },
      { word: 'Mythpat', hint: 'minecraft' },
      { word: 'Techno Gamerz', hint: 'ujjwal' },
      { word: 'Total Gaming', hint: 'ajju' },
      { word: 'Gaurav Taneja', hint: 'pilot' },
      { word: 'Kusha Kapila', hint: 'talaak' },
      { word: 'Prajakta Koli', hint: 'mostlysane' },
      { word: 'Physics Wallah', hint: 'alakh' },
      { word: 'Dhruv Rathee', hint: 'exposer' },
      { word: 'Zakir Khan', hint: 'sakht-launda' },
      { word: 'Kapil Sharma', hint: 'babuji' },
      { word: 'Vir Das', hint: 'two-india' },
      { word: 'Munawar Faruqui', hint: 'indore-lockup' },
      { word: 'Anubhav Singh Bassi', hint: 'kanpur-law' },
      { word: 'Abhishek Upmanyu', hint: 'delhi-rant' },
      { word: 'Harsh Gujral', hint: 'punjabi-airport' },
      { word: 'Aakash Gupta', hint: 'expressions' },
      { word: 'Kunal Kamra', hint: 'flight-banned' },
      { word: 'Aaditi Mittal', hint: 'lonavla' },
      { word: 'Biswa Kalyan Rath', hint: 'odiya-pretentious' },
      { word: 'Atul Khatri', hint: 'sindhi-uncle' },
      { word: 'Amit Tandon', hint: 'shaadi-rant' },
      { word: 'Daniel Fernandes', hint: 'tezgaali' },
      { word: 'Rahul Subramanian', hint: 'thakela' },
    ],
  },
  {
    name: 'Cricket Players',
    emoji: '🏏',
    locale: 'global',
    isOfficial: true,
    entries: [
      { word: 'Virat Kohli', hint: 'trophyless' },
      { word: 'MS Dhoni', hint: 'helicopter' },
      { word: 'Rohit Sharma', hint: 'neend' },
      { word: 'Sachin Tendulkar', hint: 'shatak' },
      { word: 'Rahul Dravid', hint: 'deewar' },
      { word: 'Sourav Ganguly', hint: 'lords-shirt' },
      { word: 'Yuvraj Singh', hint: 'broad-chhakka' },
      { word: 'Hardik Pandya', hint: 'natasha-divorce' },
      { word: 'Jasprit Bumrah', hint: 'yorker-sanjana' },
      { word: 'Rishabh Pant', hint: 'accident' },
      { word: 'KL Rahul', hint: 'athiya' },
      { word: 'Shubman Gill', hint: 'sara-link' },
      { word: 'AB de Villiers', hint: '360' },
      { word: 'Chris Gayle', hint: 'universe-boss' },
      { word: 'Brett Lee', hint: '4u' },
      { word: 'Wasim Akram', hint: 'swing-king' },
      { word: 'Shoaib Akhtar', hint: 'rawalpindi-express' },
      { word: 'Babar Azam', hint: 'dm-leak' },
      { word: 'Shahid Afridi', hint: 'umar' },
      { word: 'Inzamam ul Haq', hint: 'aloo' },
      { word: 'Misbah ul Haq', hint: 'tuktuk' },
      { word: 'Steve Smith', hint: 'sandpaper' },
      { word: 'David Warner', hint: 'cheat-trio' },
      { word: 'Glenn Maxwell', hint: 'double-ton' },
      { word: 'Joe Root', hint: 'ashes' },
      { word: 'Ben Stokes', hint: 'wcfinal' },
      { word: 'Rashid Khan', hint: 'afghan-spin' },
      { word: 'Suryakumar Yadav', hint: 'skyy' },
      { word: 'Sanju Samson', hint: 'kerala-dropped' },
      { word: 'Kapil Dev', hint: '1983' },
      { word: 'Virender Sehwag', hint: 'viru-tweet' },
      { word: 'Gautam Gambhir', hint: 'kkr-coach' },
      { word: 'Harbhajan Singh', hint: 'monkeygate' },
      { word: 'Mohammed Shami', hint: 'wife-case' },
      { word: 'Ricky Ponting', hint: 'ego-aussie' },
    ],
  },
  {
    name: 'Countries and Places',
    emoji: '🌍',
    locale: 'global',
    isOfficial: true,
    entries: [
      { word: 'India', hint: 'chai' },
      { word: 'Pakistan', hint: 'loadshedding' },
      { word: 'USA', hint: 'burger' },
      { word: 'China', hint: 'copy' },
      { word: 'Japan', hint: 'anime' },
      { word: 'Russia', hint: 'vodka' },
      { word: 'UK', hint: 'lutere' },
      { word: 'Australia', hint: 'kangaroo' },
      { word: 'Saudi Arabia', hint: 'tel' },
      { word: 'UAE', hint: 'burj' },
      { word: 'Nepal', hint: 'everest' },
      { word: 'Bangladesh', hint: 'ilish' },
      { word: 'Sri Lanka', hint: 'lanka-dahan' },
      { word: 'France', hint: 'eiffel' },
      { word: 'Germany', hint: 'hitler' },
      { word: 'Italy', hint: 'pizza' },
      { word: 'Brazil', hint: 'neymar' },
      { word: 'Argentina', hint: 'messi' },
      { word: 'South Korea', hint: 'bts' },
      { word: 'Egypt', hint: 'pyramid' },
      { word: 'Singapore', hint: 'sentosa' },
      { word: 'Thailand', hint: 'massage' },
      { word: 'Maldives', hint: 'honeymoon' },
      { word: 'Switzerland', hint: 'ddlj' },
      { word: 'Mauritius', hint: 'beach' },
      { word: 'Mumbai', hint: 'filmcity' },
      { word: 'Delhi', hint: 'polluted' },
      { word: 'Kashmir', hint: 'valley' },
      { word: 'Goa', hint: 'trance' },
      { word: 'Banaras', hint: 'ghaat' },
      { word: 'Jaipur', hint: 'pink-city' },
      { word: 'Manali', hint: 'honeymoon-trip' },
      { word: 'Lucknow', hint: 'tehzeeb' },
      { word: 'Bangalore', hint: 'traffic' },
      { word: 'Hyderabad', hint: 'biryani' },
    ],
  },
  {
    name: 'Nature',
    emoji: '🌿',
    locale: 'global',
    isOfficial: true,
    entries: [
      { word: 'Sun', hint: 'garmi' },
      { word: 'Moon', hint: 'chanda' },
      { word: 'Mars', hint: 'musk' },
      { word: 'Saturn', hint: 'kundli' },
      { word: 'Jupiter', hint: 'biggest' },
      { word: 'Earth', hint: 'ghar' },
      { word: 'Mercury', hint: 'thermometer' },
      { word: 'Venus', hint: 'shukra' },
      { word: 'Pluto', hint: 'demoted' },
      { word: 'Tree', hint: 'fal' },
      { word: 'River', hint: 'behti' },
      { word: 'Mountain', hint: 'trekking' },
      { word: 'Ocean', hint: 'lehrein' },
      { word: 'Forest', hint: 'junglee' },
      { word: 'Desert', hint: 'registan' },
      { word: 'Volcano', hint: 'lava' },
      { word: 'Earthquake', hint: 'kampan' },
      { word: 'Cloud', hint: 'barish' },
      { word: 'Wind', hint: 'hawa' },
      { word: 'Lightning', hint: 'garaj' },
      { word: 'Rainbow', hint: 'saatrang' },
      { word: 'Snow', hint: 'barf' },
      { word: 'Star', hint: 'twinkle' },
      { word: 'Comet', hint: 'halley' },
      { word: 'Galaxy', hint: 'milky' },
      { word: 'Black Hole', hint: 'interstellar' },
      { word: 'Tsunami', hint: '2004' },
      { word: 'Waterfall', hint: 'jhalawar' },
      { word: 'Glacier', hint: 'siachen' },
      { word: 'Tornado', hint: 'ghoomna' },
    ],
  },
  {
    name: 'Daily Use Objects',
    emoji: '🪣',
    locale: 'global',
    isOfficial: true,
    entries: [
      { word: 'Toothbrush', hint: 'saans' },
      { word: 'Pillow', hint: 'neend' },
      { word: 'Charger', hint: 'panic' },
      { word: 'Slipper', hint: 'mummy' },
      { word: 'Mirror', hint: 'selfie' },
      { word: 'Comb', hint: 'ganji' },
      { word: 'Soap', hint: 'corona' },
      { word: 'Toilet Paper', hint: 'lockdown' },
      { word: 'Towel', hint: 'geela' },
      { word: 'Bucket', hint: 'hostel' },
      { word: 'Mug', hint: 'bathroom' },
      { word: 'Fan', hint: 'shaadi' },
      { word: 'Remote', hint: 'papa-throne' },
      { word: 'Earphones', hint: 'uljhe' },
      { word: 'Specs', hint: 'saamne' },
      { word: 'Wallet', hint: 'bhulgaya' },
      { word: 'Lighter', hint: 'sutta' },
      { word: 'Diary', hint: 'secret' },
      { word: 'Pen', hint: 'exam' },
      { word: 'Pencil', hint: 'sharpener' },
      { word: 'Hairband', hint: 'ladki' },
      { word: 'Clock', hint: 'der' },
      { word: 'Spoon', hint: 'dahi' },
      { word: 'Plate', hint: 'thali' },
      { word: 'Umbrella', hint: 'monsoon' },
      { word: 'Razor', hint: 'daadhi' },
      { word: 'Helmet', hint: 'challan' },
      { word: 'Lock', hint: 'chabi-gum' },
      { word: 'Scissors', hint: 'kainchi' },
    ],
  },
  {
    name: 'Hindu Mythology',
    emoji: '🪔',
    locale: 'in',
    isOfficial: true,
    entries: [
      { word: 'Krishna', hint: 'makhan' },
      { word: 'Ram', hint: 'ayodhya' },
      { word: 'Hanuman', hint: 'seena-cheer' },
      { word: 'Ravan', hint: 'dassir' },
      { word: 'Arjun', hint: 'machhli' },
      { word: 'Shiva', hint: 'trinetra' },
      { word: 'Karna', hint: 'kavach' },
      { word: 'Bhim', hint: 'gada' },
      { word: 'Yudhishthir', hint: 'juaa' },
      { word: 'Draupadi', hint: 'cheerharan' },
      { word: 'Kunti', hint: 'mantra' },
      { word: 'Ganesha', hint: 'modak' },
      { word: 'Kartikeya', hint: 'mor' },
      { word: 'Durga', hint: 'sher-savari' },
      { word: 'Kali', hint: 'jeebh' },
      { word: 'Lakshmi', hint: 'diwali' },
      { word: 'Saraswati', hint: 'veena' },
      { word: 'Indra', hint: 'vajra' },
      { word: 'Vishnu', hint: 'sheshnaag' },
      { word: 'Brahma', hint: 'char-sir' },
      { word: 'Surya', hint: 'saatghoda' },
      { word: 'Narad', hint: 'gossip' },
    ],
  },
  {
    name: 'Anime',
    emoji: '⚔️',
    locale: 'global',
    isOfficial: true,
    entries: [
      { word: 'Naruto', hint: 'ramen' },
      { word: 'Goku', hint: 'saiyan' },
      { word: 'Luffy', hint: 'rubber' },
      { word: 'Levi', hint: 'safai' },
      { word: 'Eren Yeager', hint: 'basement' },
      { word: 'Itachi', hint: 'clan-kill' },
      { word: 'Zoro', hint: 'lost-again' },
      { word: 'Sasuke', hint: 'emo-bro' },
      { word: 'Kakashi', hint: 'mask-reader' },
      { word: 'Light Yagami', hint: 'potato-chip' },
      { word: 'Gojo', hint: 'blindfold' },
      { word: 'Saitama', hint: 'ek-mukka' },
      { word: 'Tanjiro', hint: 'checkered' },
      { word: 'One Piece', hint: 'thousand-ep' },
      { word: 'Attack on Titan', hint: 'deewar' },
      { word: 'Death Note', hint: 'naam-likho' },
      { word: 'Demon Slayer', hint: 'behan-box' },
      { word: 'Jujutsu Kaisen', hint: 'ungli' },
      { word: 'Dragon Ball Z', hint: 'powerup' },
      { word: 'Bleach', hint: 'shinigami' },
      { word: 'My Hero Academia', hint: 'quirk' },
      { word: 'Tokyo Ghoul', hint: 'kaneki' },
      { word: 'Spy x Family', hint: 'moongphali' },
      { word: 'Chainsaw Man', hint: 'denji' },
      { word: 'Doraemon', hint: 'neela-pocket' },
      { word: 'Shinchan', hint: 'paanch-saal' },
      { word: 'Pokemon', hint: 'pikachu' },
      { word: 'Beyblade', hint: 'lattu' },
      { word: 'Ninja Hattori', hint: 'kenichi' },
    ],
  },
  {
    name: 'Memes and Slang',
    emoji: '😂',
    locale: 'in',
    isOfficial: true,
    entries: [
      { word: 'Binod', hint: 'comment' },
      { word: 'Rasode mein kaun tha', hint: 'kokila' },
      { word: 'Bhai kya kar raha hai tu', hint: 'carry-trigger' },
      { word: 'Pawri ho rahi hai', hint: 'pune-girl' },
      { word: 'Mauka Mauka', hint: 'haar' },
      { word: 'Yeh chai bahut khatarnak hai', hint: 'reporter' },
      { word: 'Itni garmi', hint: 'auto-uncle' },
      { word: 'Bachpan ka pyaar', hint: 'sahdev' },
      { word: 'Kacha Badam', hint: 'bengali-vendor' },
      { word: 'Just Looking Like A Wow', hint: 'saree-line' },
      { word: 'Sharma Ji Ka Beta', hint: 'padosi' },
      { word: 'Beta Tumse Na Ho Payega', hint: 'mirzapur' },
      { word: 'Kachra Cricket', hint: 'lagaan' },
      { word: 'Saiyaara', hint: 'tiger' },
      { word: 'Tu Tu Mai Mai', hint: 'saasbahu' },
      { word: 'Bhakt', hint: 'andh' },
      { word: 'Sickular', hint: 'secular' },
      { word: 'Pseudo', hint: 'nakli' },
      { word: 'Chamcha', hint: 'boss' },
      { word: 'Jugaadu', hint: 'dhakkan' },
      { word: 'Pappu', hint: 'fail' },
      { word: 'Feku', hint: 'jhoot' },
      { word: 'Gaddar', hint: 'dhoka' },
      { word: 'Tharki', hint: 'uncle' },
      { word: 'Chichora', hint: 'sasta' },
      { word: 'Bewakoof', hint: 'moorakh' },
      { word: 'Chutiya', hint: 'beep' },
      { word: 'Jhakaas', hint: 'anil-thumb' },
      { word: 'Bawaal', hint: 'hadtaal' },
      { word: 'Setting', hint: 'chupke' },
      { word: 'Item', hint: 'munni' },
      { word: 'OP', hint: 'freefire' },
    ],
  },
  {
    name: 'Games',
    emoji: '🎮',
    locale: 'global',
    isOfficial: true,
    entries: [
      { word: 'BGMI', hint: 'indian-pubg' },
      { word: 'Free Fire', hint: 'garena' },
      { word: 'GTA', hint: 'rockstar-game' },
      { word: 'Minecraft', hint: 'blocky' },
      { word: 'Fortnite', hint: 'dance-emote' },
      { word: 'Call of Duty', hint: 'warzone' },
      { word: 'Valorant', hint: 'agents' },
      { word: 'CS:GO', hint: 'smoke-defuse' },
      { word: 'FIFA', hint: 'ea-soccer' },
      { word: 'Among Us', hint: 'sus' },
      { word: 'Roblox', hint: 'kids-meta' },
      { word: 'Mario', hint: 'plumber' },
      { word: 'Pac-Man', hint: 'ghost-eater' },
      { word: 'Tetris', hint: 'blocks-fall' },
      { word: 'Candy Crush', hint: 'level-stuck' },
      { word: 'Subway Surfers', hint: 'police-bhag' },
      { word: 'Temple Run', hint: 'monkey-bhag' },
      { word: 'Angry Birds', hint: 'pigs-mar' },
      { word: 'Clash of Clans', hint: 'townhall' },
      { word: 'Clash Royale', hint: 'tower-rush' },
      { word: 'Pokemon Go', hint: 'phone-bahar' },
      { word: 'Dota 2', hint: 'moba' },
      { word: 'Chess', hint: 'pyaada' },
      { word: 'Carrom', hint: 'striker' },
      { word: 'Ludo', hint: 'covid-game' },
      { word: 'Snake Game', hint: 'nokia-classic' },
      { word: 'Red Dead Redemption', hint: 'cowboy-ghoda' },
      { word: 'Witcher', hint: 'geralt' },
      { word: 'Elden Ring', hint: 'miyazaki-die' },
      { word: 'Cyberpunk', hint: 'broken-launch' },
      { word: 'Tekken', hint: 'jin' },
      { word: 'FAU-G', hint: 'akshay-flop' },
    ],
  },
  {
    name: 'History',
    emoji: '📜',
    locale: 'global',
    isOfficial: true,
    entries: [
      { word: 'World War 2', hint: '1939-45' },
      { word: 'World War 1', hint: 'trench' },
      { word: 'Adolf Hitler', hint: 'moustache' },
      { word: 'Cold War', hint: 'ussr-vs-usa' },
      { word: 'Indian Independence', hint: '1947-azaadi' },
      { word: 'Partition', hint: 'vibhajan' },
      { word: 'Bhagat Singh', hint: '23-fansi' },
      { word: 'Subhas Chandra Bose', hint: 'azaad-hind' },
      { word: 'Mahatma Gandhi', hint: 'lathi' },
      { word: 'Jawaharlal Nehru', hint: 'gulab' },
      { word: 'Indira Gandhi', hint: 'emergency' },
      { word: 'Jallianwala Bagh', hint: 'dyer' },
      { word: 'Akbar', hint: 'navratna' },
      { word: 'Aurangzeb', hint: 'darbari' },
      { word: 'Shivaji', hint: 'maratha' },
      { word: 'Tipu Sultan', hint: 'mysuru-tiger' },
      { word: 'Ashoka', hint: 'kalinga' },
      { word: 'Babur', hint: 'panipat' },
      { word: 'East India Company', hint: 'company-raj' },
      { word: 'French Revolution', hint: 'guillotine' },
      { word: 'Renaissance', hint: 'kala-jaagran' },
      { word: 'Berlin Wall', hint: 'tear-down' },
      { word: '9/11', hint: 'twin-tower' },
      { word: 'Hiroshima', hint: '1945-bomb' },
      { word: 'Cleopatra', hint: 'egypt-rani' },
      { word: 'Genghis Khan', hint: 'mongol' },
      { word: 'Napoleon', hint: 'chhota-france' },
      { word: 'Alexander the Great', hint: 'porus' },
      { word: 'Chandragupta Maurya', hint: 'chanakya-shishya' },
      { word: 'Rani Lakshmibai', hint: 'jhansi' },
    ],
  },
  {
    name: 'Movies',
    emoji: '🎬',
    locale: 'global',
    isOfficial: true,
    entries: [
      { word: 'Sholay', hint: 'gabbar' },
      { word: 'DDLJ', hint: 'raj-simran' },
      { word: '3 Idiots', hint: 'rancho' },
      { word: 'PK', hint: 'transistor' },
      { word: 'Dangal', hint: 'kushti-bahen' },
      { word: 'Bahubali', hint: 'katappa' },
      { word: 'KGF', hint: 'rocky-bhai' },
      { word: 'Pushpa', hint: 'jhukega-nahin' },
      { word: 'Avatar', hint: 'neela-cameron' },
      { word: 'Avengers Endgame', hint: 'thanos' },
      { word: 'Inception', hint: 'dream-spin' },
      { word: 'Interstellar', hint: 'tesseract' },
      { word: 'Joker', hint: 'haha' },
      { word: 'Batman', hint: 'bruce-wayne' },
      { word: 'Iron Man', hint: 'tony-arc' },
      { word: 'Spider-Man', hint: 'tobey-tom-andrew' },
      { word: 'Harry Potter', hint: 'hogwarts' },
      { word: 'Lord of the Rings', hint: 'ring-frodo' },
      { word: 'Matrix', hint: 'redpill' },
      { word: 'Pulp Fiction', hint: 'tarantino' },
      { word: 'Godfather', hint: 'offer' },
      { word: 'Oppenheimer', hint: 'trinity' },
      { word: 'Barbie', hint: 'pink-everything' },
      { word: 'Squid Game', hint: '456' },
      { word: 'Money Heist', hint: 'bella-ciao' },
      { word: 'Stranger Things', hint: 'upside-down' },
      { word: 'Friends', hint: 'ross-rachel' },
      { word: 'Game of Thrones', hint: 'iron-throne' },
      { word: 'Sacred Games', hint: 'ashwathama' },
      { word: 'Animal', hint: 'alpha-ranbir' },
      { word: 'Jawan', hint: 'srk-double' },
      { word: 'Pathaan', hint: 'comeback-srk' },
      { word: 'Stree', hint: 'kal-aana' },
      { word: 'RRR', hint: 'naatu' },
      { word: 'Kabir Singh', hint: 'preeti-vodka' },
      { word: 'Drishyam', hint: 'alibi' },
      { word: 'Andhadhun', hint: 'blind-pianist' },
    ],
  },
  {
    name: 'World Monuments',
    emoji: '🗿',
    locale: 'global',
    isOfficial: true,
    entries: [
      { word: 'Taj Mahal', hint: 'mumtaz' },
      { word: 'Eiffel Tower', hint: 'love-proposal' },
      { word: 'Statue of Liberty', hint: 'torch-NY' },
      { word: 'Great Pyramid', hint: 'pharaoh-tomb' },
      { word: 'Great Wall', hint: 'moon-dikhe' },
      { word: 'Big Ben', hint: 'london-clock' },
      { word: 'Leaning Tower of Pisa', hint: 'tilted' },
      { word: 'Burj Khalifa', hint: 'sky-tallest' },
      { word: 'Statue of Unity', hint: 'sardar' },
      { word: 'India Gate', hint: 'amar-jawan' },
      { word: 'Charminar', hint: 'chaar-minaar' },
      { word: 'Red Fort', hint: '15august-speech' },
      { word: 'Qutub Minar', hint: 'delhi-pillar' },
      { word: 'Lotus Temple', hint: 'phool-mandir' },
      { word: 'Gateway of India', hint: 'mumbai-arch' },
      { word: 'Hawa Mahal', hint: 'khidkiyaan' },
      { word: 'Ajanta Caves', hint: 'guphaa-painting' },
      { word: 'Konark Sun Temple', hint: 'wheel-rath' },
      { word: 'Sphinx', hint: 'lion-face' },
      { word: 'Christ the Redeemer', hint: 'rio-jesus' },
      { word: 'Colosseum', hint: 'gladiator' },
      { word: 'Stonehenge', hint: 'rocks-mystery' },
      { word: 'Machu Picchu', hint: 'incan-peak' },
      { word: 'Angkor Wat', hint: 'cambodia-temple' },
      { word: 'Sydney Opera House', hint: 'shell-roof' },
      { word: 'Mount Rushmore', hint: 'presidents-rock' },
      { word: 'Buckingham Palace', hint: 'queen-ghar' },
      { word: 'Kaaba', hint: 'haj' },
      { word: 'Vatican', hint: 'pope' },
      { word: 'Petra', hint: 'jordan-rose' },
      { word: 'Hagia Sophia', hint: 'istanbul' },
      { word: 'Acropolis', hint: 'athens' },
      { word: 'Golden Temple', hint: 'amritsar-langar' },
    ],
  },
  {
    name: 'Foods',
    emoji: '🍛',
    locale: 'global',
    isOfficial: true,
    entries: [
      { word: 'Biryani', hint: 'dum' },
      { word: 'Butter Chicken', hint: 'creamy-orange' },
      { word: 'Samosa', hint: 'tribhuj-chai' },
      { word: 'Pani Puri', hint: 'phuchka' },
      { word: 'Vada Pav', hint: 'mumbai-burger' },
      { word: 'Dosa', hint: 'south-roti' },
      { word: 'Idli', hint: 'soft-rice' },
      { word: 'Chole Bhature', hint: 'punjabi-fulka' },
      { word: 'Rajma Chawal', hint: 'weekend-meal' },
      { word: 'Pav Bhaji', hint: 'mashed-veg' },
      { word: 'Chowmein', hint: 'street-noodle' },
      { word: 'Momos', hint: 'tibetan' },
      { word: 'Gulab Jamun', hint: 'chashni' },
      { word: 'Jalebi', hint: 'tedhi-meedhi' },
      { word: 'Rasgulla', hint: 'bengali-mishti' },
      { word: 'Kheer', hint: 'chawal-meetha' },
      { word: 'Maggi', hint: '2-minute' },
      { word: 'Pasta', hint: 'white-sauce' },
      { word: 'Sushi', hint: 'raw-fish' },
      { word: 'Tacos', hint: 'mexican-shell' },
      { word: 'Shawarma', hint: 'arab-wrap' },
      { word: 'Mango', hint: 'aam-raja' },
      { word: 'Khichdi', hint: 'bimar-food' },
      { word: 'Nihari', hint: 'sunday-special' },
      { word: 'Haleem', hint: 'ramzan' },
      { word: 'Halwa', hint: 'atta-meetha' },
      { word: 'Falooda', hint: 'rose-vermicelli' },
      { word: 'Lassi', hint: 'punjabi-thanda' },
      { word: 'Dum Aloo', hint: 'kashmiri-aloo' },
      { word: 'Litti Chokha', hint: 'bihari' },
      { word: 'Misal Pav', hint: 'spicy-pav' },
      { word: 'Pizza', hint: 'cheesy-italian' },
      { word: 'Burger', hint: 'patty-bun' },
      { word: 'Ramen', hint: 'naruto-soup' },
    ],
  },
  {
    name: 'Mind Bender',
    emoji: '🧠',
    locale: 'global',
    isOfficial: true,
    entries: [
      { word: 'Zeus', hint: 'thunder-greek' },
      { word: 'Medusa', hint: 'snake-hair' },
      { word: 'Achilles', hint: 'heel-weak' },
      { word: 'Loki', hint: 'trickster-norse' },
      { word: 'Thor', hint: 'hammer-norse' },
      { word: 'Odin', hint: 'one-eye' },
      { word: 'Atlantis', hint: 'doobi-shahar' },
      { word: 'Pompeii', hint: 'raakh-buried' },
      { word: 'Bigfoot', hint: 'sasquatch' },
      { word: 'Loch Ness Monster', hint: 'scotland-paani' },
      { word: 'Yeti', hint: 'himalayan-snowman' },
      { word: 'Area 51', hint: 'alien-base' },
      { word: 'Illuminati', hint: 'triangle-eye' },
      { word: 'Bermuda Triangle', hint: 'ships-gayab' },
      { word: 'Voynich Manuscript', hint: 'uncracked-book' },
      { word: 'DB Cooper', hint: 'parachute-thief' },
      { word: 'Zodiac Killer', hint: 'uncaught' },
      { word: "Schrodinger's Cat", hint: 'alive-dead' },
      { word: 'Stockholm Syndrome', hint: 'hostage-pyaar' },
      { word: 'Dunning Kruger', hint: 'overconfident-dumb' },
      { word: 'Tardigrade', hint: 'indestructible-bug' },
      { word: 'Mantis Shrimp', hint: 'punch-fastest' },
      { word: 'Mandela Effect', hint: 'yaad-galat' },
      { word: 'Streisand Effect', hint: 'chhupao-zyada' },
      { word: "Murphy's Law", hint: 'kuchbhi-galat' },
      { word: 'Mariana Trench', hint: 'deepest-samudra' },
      { word: 'Easter Island', hint: 'bade-sir-statue' },
      { word: 'Nazca Lines', hint: 'asmaan-se-dikhe' },
      { word: 'Fermi Paradox', hint: 'alien-kahan' },
      { word: 'Roswell', hint: 'ufo-1947' },
      { word: 'Antikythera Mechanism', hint: 'ancient-computer' },
      { word: 'Dyatlov Pass', hint: 'russia-nine-dead' },
      { word: 'Tunguska Event', hint: 'siberia-blast' },
      { word: 'Roanoke Colony', hint: 'lost-village' },
      { word: 'Pareto Principle', hint: '80-20' },
      { word: 'Stanford Prison', hint: 'guard-cruel' },
      { word: 'Bystander Effect', hint: 'koi-help-nahi' },
      { word: 'Trolley Problem', hint: 'lever-jaan' },
    ],
  },
];
